### ISSUE TITLE
Incorrect Euclidean division in Python 3

### ISSUE THREAD

**Issue by ViviCoder** [weaverba137/pydl#19]
In Python 3, the Euclidean division needs to be done using // instead of /.
This causes the test of the median to fail with the following backtrace:
```
        from scipy.signal import medfilt, medfilt2d
        if width is None:
            if axis is None:
                f = array.flatten()
                if f.size % 2 == 1 or even:
                    return np.median(array)
                else:
                    i = f.argsort()
>                   return f[i[f.size/2]]
E                   IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
 
pydl/median.py:53: IndexError
```

**Comment by weaverba137** [comment]
Could you please provide a snippet that reproduces this error?

**Comment by ViviCoder** [comment]
@weaverba137 To reproduce the error, I think you have to use the new version of NumPy (1.12).
Before, you could use floats such as 1.0 as indices, but now you have to use integers.

**Comment by weaverba137** [comment]
This is fixed in the hmf-object branch and will be incorporated into the next release.
