### ISSUE TITLE
Citable record?

### ISSUE THREAD

**Issue by adrn** [weaverba137/pydl#36]
We're planning to reference and cite all Astropy affiliated packages in the upcoming Astropy v2.0 paper. I couldn't find a citable record for this package - are you interested in creating one so that we can cite it? For example, you can create a [zenodo](zenodo.org) record and just comment back here to let me know that it's done. Please also let me know if you'd like to opt out of a citation and we'll just link to the package. Thanks!

**Comment by weaverba137** [comment]
Is there some reason *not* to use [ASCL](http://ascl.net/)?

**Comment by adrn** [comment]
My understanding is that ASCL is a registry of software, but does not produce true DOI's -- I think it's more of a database of software. But I could be wrong about that.

**Comment by weaverba137** [comment]
Ah, OK.  I took a quick glance, & it was not obvious that ASCL provides a DOI.  I'll look into zenodo.  My concern though is that ASCL has been around for years, but I've never heard of zenodo.  Is that really the choice for long-term curation of citations?

**Comment by weaverba137** [comment]
@adrn, I now have a zenodo *account*, but I have no idea whatsoever what to do now.  Please provide instructions on how to proceed.

**Comment by weaverba137** [comment]
Alternatively, does the term "citeable record" imply a DOI by definition, or is it possible to have a "citeable record" that does not have a DOI?

**Comment by weaverba137** [comment]
I've bit the bullet & am prepared to create a Zenodo record for this, but it appears that publication only happens on a *new* release.  I need to publish an *existing* release.  Please help!

**Comment by adrn** [comment]
I think you can download a zip of the last release of Pydl (from GitHub, e.g. https://github.com/weaverba137/pydl/archive/0.6.0.zip) and upload this to Zenodo manually. You have to enter some info manually but it should be possible to create an entry from an existing release. Let me know if you get stuck - I've done this a few times.

**Comment by weaverba137** [comment]
OK, that worked: https://doi.org/10.5281/zenodo.1095150.  I'll submit a PR on the Astropy 2 paper to add the citation.

PS, for the record, this guide was helpful: https://guides.github.com/activities/citable-code/

I'd still like to discuss whether the definition of "citation" requires a DOI by necessity, but that's separate from this issue.
