### ISSUE TITLE
Missing setup.py in PyPI tarball

### ISSUE THREAD

**Issue by ViviCoder** [weaverba137/pydl#65]
The tarball of version 1.0.0rc2 available on PyPI is missing setup.py.

**Comment by weaverba137** [comment]
That may be a feature, not a bug.  `setup.py` is deprecated anyway.  Does the package fail to install with pip?

**Comment by weaverba137** [comment]
1.0.0rc2 has been yanked.  Use 1.0.0rc1, there is no difference in the code, API, etc.

**Comment by weaverba137** [comment]
If you absolutely must use 1.0.0rc2, use `pip install git+https://github.com/weaverba137/pydl.git@1.0.0rc2`.
