### ISSUE TITLE
Unexpected iaxis argument in call to djs_maskinterp()

### ISSUE THREAD

**Issue by tdwelly** [weaverba137/pydl#70]
Hi,
I noticed a likely typo here: https://github.com/weaverba137/pydl/blob/main/pydl/pydlspec2d/spec2d.py#L439
Within the function filter_thru(), djs_maskinterp() is called with argument 'iaxis', but expects 'axis' instead: 
https://github.com/weaverba137/pydl/blob/main/pydl/pydlutils/image.py#L63
Simply renaming the argument (iaxis->axis) allows the function to run to completion...but expert eyes are needed to tell if this is the correct behaviour.
Many thanks!

**Comment by weaverba137** [comment]
That is clearly a bug that may be left over from the original IDL code. I have fixed it in the branch `endian-test`, if you want to test that yourself. If you find further issues, please report them on #69.

Fixed by d8a5369.
