### ISSUE TITLE
pydl no longer compatible with astropy 6

### ISSUE THREAD

**Issue by havok2063** [weaverba137/pydl#74]
WIth astropy 6.0, they removed the `update_default_config` method.  See https://docs.astropy.org/en/stable/changelog.html#api-changes.  Discovered this in my project CI with pydl 0.7.   

In the short term, I can pin to `astropy < 6`.  You may want to put in an explicit `astropy<6` in your dependencies, or a better long-term solution may be to try to resolve it, so people can still use `pydl` with `astropy > 6`.

**Comment by weaverba137** [comment]
PyDL v1.0.0 should be released very soon and `update_default_config` has already been removed from the code.

**Comment by havok2063** [comment]
Nice!

**Comment by weaverba137** [comment]
@havok2063, The v1.0.0 tag exists, so you could go ahead and test against that, it will probably be another day or so before 1.0.0 appears on PyPI.

**Comment by weaverba137** [comment]
@havok2063, version 1.0.0 is on PyPI. It should also be available on conda-forge. I'm going to assume that fixes you're issue.

**Comment by havok2063** [comment]
Yes this fixes it!  Thanks!
