### ISSUE TITLE
bspline.__init__() got an unexpected keyword argument 'groupbadpix'

### ISSUE THREAD

**Issue by WenkeRen** [weaverba137/pydl#77]
Hi,

Thanks for your wonderful code. I found an error when I'm trying to run `pydlspec2d.spec2d.combine1fiber` function. The traceback is as follow:

> stack_flux, stack_ivar = spec2d.combine1fiber(loglam_cube, flux_cube, loglam_ref, ivar_cube)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/site-packages/pydl/pydlspec2d/spec2d.py", line 232, in combine1fiber
>     sset, bmask = iterfit(inloglam_r[ss],
>                   ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/site-packages/pydl/pydlutils/bspline.py", line 608, in iterfit
>     sset = bspline(xdata[xsort[maskwork]], **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: bspline.__init__() got an unexpected keyword argument 'groupbadpix'

To me, it is quite straightforward so I don't provide examples for this error. Probably, due to some update in bspline class, you update the parameter list in the `bspline.__init__` but forgot the argument `groupbadpix`. 

Let me know if you need more information about this issue.

Cheers

**Comment by weaverba137** [comment]
Thank you @WenkeRen, I don't think `groupbadpix` was ever implemented, so it's an extraneous argument rather than a missing argument. I will need to investigate further.

**Comment by WenkeRen** [comment]
True. To make it work in my side, I just commented this parameter out and so far everything works fine for me.
