### ISSUE TITLE
I/O shape conflict in pydl.goddard.astro.airtovac

### ISSUE THREAD

**Issue by kbwestfall** [weaverba137/pydl#8]
When providing airtovac with a multi-dimensional array, I get the following shape casting conflict:

`from pydl.goddard.astro import airtovac`
`import numpy`
`wave = numpy.arange(1000,dtype=float).reshape(2,500)+5000`
`airtovac(wave)`

`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pydl/goddard/astro.py", line 29, in airtovac`
`    vacuum = zeros(air.size, dtype=air.dtype) + air`
`ValueError: operands could not be broadcast together with shapes (1000,) (2,500)`

I think this can be solved by changing `air.size` to `air.shape`

**Comment by weaverba137** [comment]
This is fixed on the master branch.
