### ISSUE TITLE
pydl Mangle issue(s)

### ISSUE THREAD

**Issue by mdipompe** [weaverba137/pydl#9]
There seem to be a few issues in pydl.pydlutils.mangle, and I think I've traced it to cap_distance.

In cap_distance, if you supply xyz points (ncol = 3), line 401 is:
`xyz = point`
when it should be:
`xyz = points`

In the next steps, when the dot product is taken between the positions and the cap centers, it should be taken with the xyz positions, and not points.  Line 404 reads:
`dotprod = np.dot(points, x)`
when it should be:
`dotprod = np.dot(xyz, x)`

(Apologies if my understanding is incorrect and the errors are due to misuse rather than real issues, I'm fairly new to python!)

**Comment by weaverba137** [comment]
Most likely those are genuine errors.  I will take a closer look.
